# Generated by Django 2.2 on 2019-09-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='event',
            field=models.ManyToManyField(to='eventFinderApp.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='venue name', max_length=200),
        ),
    ]
