# Generated by Django 2.2 on 2019-09-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0002_auto_20190907_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
